services:
  scalyr-agent:
    image: scalyr/scalyr-agent-docker-json:latest
    container_name: scalyr-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SCALYR_API_KEY: "${SCALYR_API_KEY}"
      SCALYR_SERVER: "${SCALYR_SERVER}"
    volumes:
      - "${HOST_LOG_DIR}:/host_logs:ro"
      - "./docker.json:/etc/scalyr-agent-2/agent.d/docker.json:ro"
